### ISSUE TITLE
Error running model_RGB.train()

### ISSUE THREAD

**Issue by BinWang28** [chenxinpeng/S2VT#9]
Thanks for your detailed work.
I got an error running the code. Does that mean that there is something wrong with my video dataset?

In [2]: model_RGB.train()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-6f037f1f771f> in <module>()
----> 1 model_RGB.train()

/home/binwang/Documents/S2VT/model_RGB.py in train()
    247 
    248 def train():
--> 249     train_data = get_video_train_data(video_train_data_path, video_train_feat_path)
    250     train_captions = train_data['Description'].values
    251     test_data = get_video_test_data(video_test_data_path, video_test_feat_path)

/home/binwang/Documents/S2VT/model_RGB.py in get_video_train_data(video_data_path, video_feat_path)
    190     video_data = video_data[video_data['Description'].map(lambda x: isinstance(x, str))]
    191 
--> 192     unique_filenames = sorted(video_data['video_path'].unique())
    193     train_data = video_data[video_data['video_path'].map(lambda x: x in unique_filenames)]
    194     return train_data

/usr/lib/python2.7/dist-packages/pandas/core/frame.pyc in __getitem__(self, key)
   1967             return self._getitem_multilevel(key)
   1968         else:
-> 1969             return self._getitem_column(key)
   1970 
   1971     def _getitem_column(self, key):

/usr/lib/python2.7/dist-packages/pandas/core/frame.pyc in _getitem_column(self, key)
   1974         # get column
   1975         if self.columns.is_unique:
-> 1976             return self._get_item_cache(key)
   1977 
   1978         # duplicate columns & possible reduce dimensionality

/usr/lib/python2.7/dist-packages/pandas/core/generic.pyc in _get_item_cache(self, item)
   1089         res = cache.get(item)
   1090         if res is None:
-> 1091             values = self._data.get(item)
   1092             res = self._box_item_values(item, values)
   1093             cache[item] = res

/usr/lib/python2.7/dist-packages/pandas/core/internals.pyc in get(self, item, fastpath)
   3209 
   3210             if not isnull(item):
-> 3211                 loc = self.items.get_loc(item)
   3212             else:
   3213                 indexer = np.arange(len(self.items))[isnull(self.items)]

/usr/lib/python2.7/dist-packages/pandas/core/index.pyc in get_loc(self, key, method, tolerance)
   1757                                  'backfill or nearest lookups')
   1758             key = _values_from_object(key)
-> 1759             return self._engine.get_loc(key)
   1760 
   1761         indexer = self.get_indexer([key], method=method,

/usr/lib/python2.7/dist-packages/pandas/index.so in pandas.index.IndexEngine.get_loc (pandas/index.c:3979)()

/usr/lib/python2.7/dist-packages/pandas/index.so in pandas.index.IndexEngine.get_loc (pandas/index.c:3843)()

/usr/lib/python2.7/dist-packages/pandas/hashtable.so in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12265)()

/usr/lib/python2.7/dist-packages/pandas/hashtable.so in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:12216)()

KeyError: 'video_path'

**Comment by weiran96** [comment]
I have the same problem, do you solve it ?

**Comment by smallflyingpig** [comment]
http://pandas.pydata.org/pandas-docs/version/0.19.2/generated/pandas.DataFrame.irow.html
the error is bacause irow() is DEPRECATED, use iloc[] to instead. That is `current_train_data = train_data.groupby('video_path').apply(lambda x: x.iloc[np.random.choice(len(x))])`
for Line 304

**Comment by WhuRan** [comment]
You should divide extracted rgb_feats into test and train.

**Comment by holibert** [comment]
@weiran96 I have met with the same problem. It works.

**Comment by mayhammad277** [comment]
https://github.com/chenxinpeng/S2VT/issues/9#issuecomment-356729559 didnt work  for me still the same error

**Comment by mayhammad277** [comment]
![image](https://user-images.githubusercontent.com/35504664/52090182-46e37500-25b9-11e9-8b38-2f1cc613058d.png)

**Comment by Scentedtea0210** [comment]
@m-and-ms Hello,Did you solve this problem?

**Comment by mayhammad277** [comment]
yes , i think it was a problem related to the version of tensorflow  i guess the version was 1.1 but i dont quite remember that was a year ago :D

**Comment by ZiYinHong** [comment]
> yes , i think it was a problem related to the version of tensorflow i guess the version was 1.1 but i dont quite remember that was a year ago :D

I have met with the same problem,what tensorflow and python version do you use?

**Comment by abhirup2691** [comment]
Having the same problem. trying to run the code in Colab and unable to fix this problem.
